version: "2.1"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
